trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dicecontainer'
  version: 'latest'
  # version: '39'
  location: 'eastus'  # Change this to your desired location
  aciName: 'thiscontainerinstanc'
  
steps:

- task: AzureKeyVault@2
  displayName: Get Secrets from Key Vault
  inputs:
    azureSubscription: 'dicePipeline'
    KeyVaultName: 'thisdicekeyvault'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    containerRegistry: 'dockerSC'
    command: 'login'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'dockerSC'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'dockerSC'
    repository: '$(imageName)'
    command: 'push'
    tags: '$(version)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'dicePipeline'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #!/bin/bash
      
      echo "Starting Azure CLI script..."
      
      echo "Logging in to ACR..."
      az acr login --name $(acrName)
      
      echo "Creating or updating Azure Container Instance..."
      az container create \
        --resource-group $(resourceGroupName) \
        --name $(aciName) \
        --image $(acrName).azurecr.io/$(imageName):$(version) \
        --cpu 1 \
        --memory 1 \
        --restart-policy Never \
        --registry-username $(acrName) \
        --registry-password $(acrPassword) \
        --environment-variables 'server'='$(server)' 'database'='$(database)' 'username'='$(username)' 'password'='$(password)' 'connectionString'='$(connectionString)' 'containerName'='$(containerName)' 'jobDataFile'='$(jobDataFile)' 'rawDataFile'='$(rawDataFile)' 
    displayName: 'Run Azure CLI Script'


