trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'thisresourcegroup'
  acrName: 'thisacr'
  imageName: 'dicecontainer'
  version: 'v1'
  location: 'eastus'  # Change this to your desired location
  aciName: 'thiscontainerinstancemaybe'
  imageTag: 'latest'
  managedIdentity: '/subscriptions/e4cf2944-5342-4787-b990-418828e39bfc/resourcegroups/thisresourcegroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/thismyidentity'
  # DataBase
  server: 'dice-sql.database.windows.net'
  database: 'dice_sql_database'
  username: 'iAmRoot'
  password: 'Qwerty@213'

  # Azure
  connectionString: 'DefaultEndpointsProtocol=https;AccountName=dicestorage01;AccountKey=iIl/9k0FD6bMLck2NRkLLEtUTQ6p7v0UUk6v/bG5Aotxc+rmmAH5o10Pt0NArA21lZkHX7AFNFdb+ASt7i9zKA==;EndpointSuffix=core.windows.net'
  containerName: 'dice-data'
  jobDataFile: 'jobData.json'
  rawDataFile: 'rawData.json'
  
steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: '$(acrName).azurecr.io'
    azureSubscriptionEndpoint: 'dicePipeline'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    dockerfile: '**/Dockerfile'
    containerRegistry: '$(acrName).azurecr.io'
    repository: '$(imageName)'
    tags: |
      $(version)

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: push
    containerRegistry: '$(acrName).azurecr.io'
    repository: '$(imageName)'
    tags: |
      $(version)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'dicePipeline'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #!/bin/bash
      
      echo "Starting Azure CLI script..."
      
      echo "Logging in to ACR..."
      az acr login --name $(acrName)
      
      echo "Creating or updating Azure Container Instance..."
      az container create \
        --resource-group $(resourceGroupName) \
        --name $(aciName) \
        --image $(acrName).azurecr.io/$(imageName):$(imageTag) \
        --assign-identity $(managedIdentity) \
        --cpu 1 \
        --memory 1 \
        --restart-policy Never \
        --registry-username $(acrName) \
        --registry-password $(acrPassword) \ # Ensure to handle secrets securely
        --environment-variables server=$(server) database=$(database) username=$(username) password=$(password) connectionString=$(connectionString) containerName=$(containerName) jobDataFile=$(jobDataFile) rawDataFile=$(rawDataFile) 
    displayName: 'Run Azure CLI Script'
